export const cardsData = [
  {
    id: 1,
    title: "Рестораны",
    body: "qweasdasdqwe",
    link: "resturant",
    img: "/src/assets/qwerty/8541862.webp",
  },
  {
    id: 2,
    title: "Певцы",
    body: "qweasdasdqwe",
    link: "singer",
    img: "/src/assets/qwerty/8796785.webp",
  },
  {
    id: 3,
    title: "Оформление",
    body: "qweasdasdqwe",
    link: "oformlenie",
    img: "/src/assets/qwerty/8715396.webp",
  },
  {
    id: 4,
    title: "Фотографы",
    body: "qweasdasdqwe",
    link: "photo",
    img: "/src/assets/qwerty/7525255.webp",
  },
  {
    id: 5,
    title: "Музыканты",
    body: "qweasdasdqwe",
    link: "music",
    img: "/src/assets/qwerty/8769954.webp",
  },
  {
    id: 6,
    title: "Машины",
    body: "qweasdasdqwe",
    link: "cars",
    img: "/src/assets/qwerty/8624978.webp",
  },
  {
    id: 7,
    title: "Салоны",
    body: "qweasdasdqwe",
    link: "salons",
    img: "/src/assets/qwerty/10306502.webp",
  },
  {
    id: 7,
    title: "Ведущие",
    body: "qweasdasdqwe",
    link: "vedushui",
    img: "/src/assets/qwerty/7097523.webp",
  },
];
