export const cardsData = [
  {
    id: 1,
    title: "Рестораны",
    body: "qweasdasdqwe",
    link: "resturant",
    img: "/src/assets/8541862.png",
  },
  {
    id: 2,
    title: "Певцы",
    body: "qweasdasdqwe",
    link: "singer",
    img: "/src/assets/8796785.png",
  },
  {
    id: 3,
    title: "Оформление",
    body: "qweasdasdqwe",
    link: "oformlenie",
    img: "/src/assets/8715396.png",
  },
  {
    id: 4,
    title: "Фотографы",
    body: "qweasdasdqwe",
    link: "photo",
    img: "/src/assets/7525255.png",
  },
  {
    id: 5,
    title: "Музыканты",
    body: "qweasdasdqwe",
    link: "music",
    img: "/src/assets/8769954.png",
  },
  {
    id: 6,
    title: "Машины",
    body: "qweasdasdqwe",
    link: "cars",
    img: "/src/assets/8624978.png",
  },
  {
    id: 7,
    title: "Салоны",
    body: "qweasdasdqwe",
    link: "salons",
    img: "/src/assets/10306502.png",
  },
  {
    id: 7,
    title: "Ведущие",
    body: "qweasdasdqwe",
    link: "vedushui",
    img: "/src/assets/7097523.png",
  },
];
